name: Update Certain Game Data
on:
    # schedule:
    #   - cron: 0 3 * * *
    workflow_dispatch:
permissions:
    contents: write
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout master
          uses: actions/checkout@v4
        - name: Set up python
          uses: actions/setup-python@v5
          with:
            python-version: 3.10.11
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
        - name: Update Data
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            python3 update.py
        - name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: Update Certain Game Data